### ISSUE TITLE
官网失效

### ISSUE THREAD

**Issue by Renkai** [zhhmn/huma-rime#1]
https://tiger-code.com/
<img width="698" alt="image" src="https://github.com/zhhmn/huma-rime/assets/3381789/23044895-01d8-49c1-8749-2eca3b5a43ca">

下面这个似乎是新官网?
https://huma-next.vercel.app/

**Comment by Frefreak** [comment]
首页更新了，感谢提醒

**Comment by Frefreak** [comment]
官网好像恢复了，还是改回tiger-code吧
