### ISSUE TITLE
那么大的项目为什么就我一个Star？

### ISSUE THREAD

**Issue by kchen0x** [zhhmn/huma-rime#2]
诧异。

**Comment by Frefreak** [comment]
也不算大项目，只是把官方的包定期自动化拉过来。

本身用户群体就少，还用git的就又少了一截。而且这个repo没宣传过（可能官方都不知道有这么个项目）

**Comment by kchen0x** [comment]
这可是“虎码”谷歌搜索的第三个结果🤔🤔

**Comment by Frefreak** [comment]
绝大多数人估计直接进网盘下载了，我当时也是想记录下每次变更内容才开这个的。

issue里面我们就不讨论这个了，如果想交流我们可以先通过邮件加联系方式哈
